const data = {
    products:[
        {
            _id:'1',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 1000,
            brand: 'Nike',
            rating: '4.5',
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'2',
            name: 'Tommy Slim Shirt',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price: 150,
            countInStock: 5,
            brand: 'TOMMY',
            rating: '4.8',
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'3',
            name: 'Adidas fit Shirt',
            category: 'Shirts',
            image: '/images/p3.jpg',
            price: 89,
            countInStock: 1,
            brand: 'Adidas',
            rating: '4.2',
            numReviews: 9,
            description: 'high quality product',
        },
        {
            _id:'4',
            name: 'Calvin klein Slim pants',
            category: 'Pants',
            image: '/images/p4.jpg',
            price: 90,
            countInStock: 12,
            brand: 'Calvin klein',
            rating: '4.7',
            numReviews: 12,
            description: 'high quality product',
        },
        {
            _id:'5',
            name: 'Hugo Boss Shoes',
            category: 'Shoes',
            image: '/images/p5.jpg',
            price: 160,
            countInStock: 0,
            brand: 'Hugo Boss',
            rating: '4.9',
            numReviews: 22,
            description: 'high quality product',
        },
        {
            _id:'6',
            name: 'Puma Sneakers',
            category: 'Sneakers',
            image: '/images/p6.jpg',
            price: 10000,
            countInStock: 10,
            brand: 'Puma',
            rating: '4.1',
            numReviews: 15,
            description: 'high quality product',
        },
    ]
}
export default data;